version: '3.8'

services:
  mysqldb:
    container_name: mysql_db
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - db:/var/lib/mysql/
    env_file:
    - docker.env
    networks:
    - mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    env_file:
    - docker.env
    depends_on:
      - mysqldb
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
volumes: 
  db: